# TGAT 網路攻擊檢測系統配置文件

# 資料相關配置
data:
  # 資料集路徑
  path: ./data
  # 測試集比例
  test_size: 0.2
  # 隨機種子
  random_state: 42
  # 批次大小
  batch_size: 1000

# 圖結構相關配置
graph:
  # 時間窗口大小（秒）
  temporal_window: 600  # 10分鐘

# 模型相關配置
model:
  # 隱藏層維度
  hidden_dim: 64
  # 輸出層維度
  out_dim: 64
  # 時間編碼維度
  time_dim: 16
  # TGAT 層數
  num_layers: 2
  # 注意力頭數
  num_heads: 4
  # 丟棄率
  dropout: 0.1

# 訓練相關配置
train:
  # 學習率
  lr: 0.001
  # 權重衰減係數
  weight_decay: 0.00001
  # 訓練輪數
  epochs: 50
  # 早停耐心值
  patience: 10
  # 訓練批次大小
  batch_size: 1000

# 即時檢測相關配置
detection:
  # 攻擊判定閾值
  threshold: 0.7
  # 視覺化窗口大小
  window_size: 100
  # 更新間隔（秒）
  update_interval: 1

# 輸出路徑配置
output:
  # 模型儲存路徑
  model_dir: ./models
  # 結果儲存路徑
  result_dir: ./results
  # 視覺化結果儲存路徑
  visualization_dir: ./visualizations