# 記憶體優化版 TGAT 網路攻擊檢測系統配置文件 - 快速高準確率版本
# 資料相關配置 - 平衡記憶體使用和效率的設置
data:
  path: "./data"                  # 資料集路徑
  test_size: 0.3                  # 測試集比例
  random_state: 42                # 隨機種子
  batch_size: 512                 # 使用較大的批次大小提高效率

  # 記憶體優化相關配置 - 平衡設置
  use_memory_mapping: true        # 使用記憶體映射加速讀取
  save_preprocessed: true         # 保存預處理資料以便重用
  preprocessed_path: "./recode/preprocessed_data"
  incremental_loading: true       # 使用增量式加載減少記憶體使用
  chunk_size_mb: 1024             # 增加塊大小以減少磁碟IO次數
  use_compression: true           # 啟用壓縮以減少記憶體使用
  compression_format: "gzip"      # gzip提供良好的壓縮率與解壓速度平衡

  # 資料採樣相關配置 - 更高效的設置
  use_sampling: true              # 啟用資料採樣以減少資料量
  sampling_strategy: "stratified" # 使用分層採樣確保各類攻擊模式都有足夠表示
  sampling_ratio: 0.1             # 使用更多資料提高模型準確度 (使用10%的資料)
  min_samples_per_class: 1000     # 確保每個類別有足夠的樣本

# 圖結構相關配置 - 效能優化設置
graph:
  temporal_window: 300            # 使用更合理的時間窗口

  # 記憶體優化相關配置
  use_subgraph_sampling: true     # 使用子圖採樣加速訓練
  max_nodes_per_subgraph: 5000    # 增加子圖大小提高模型效果
  max_edges_per_subgraph: 10000   # 增加子圖邊數提高模型效果
  use_sparse_representation: true # 使用稀疏表示節省記憶體
  edge_batch_size: 5000           # 增加邊批次處理大小提高效率
  prune_inactive_nodes: true      # 清理不活躍節點
  inactive_threshold: 1800        # 使用更合理的不活躍閾值減少圖重建次數 (30分鐘)

# 模型相關配置 - 平衡效能和記憶體的設置
model:
  input_dim: 128                  # 輸入特徵維度
  hidden_dim: 64                  # 隱藏層維度
  out_dim: 64                     # 輸出維度
  time_dim: 16                    # 時間編碼維度
  num_layers: 2                   # 層數
  num_heads: 4                    # 注意力頭數
  dropout: 0.2                    # 丟棄率
  num_classes: 2                  # 分類數量 (如二分類問題)

  # 記憶體優化相關配置
  use_mixed_precision: true       # 使用混合精度加速訓練
  use_gradient_accumulation: true # 啟用梯度累積
  gradient_accumulation_steps: 4  # 梯度累積步數
  use_gradient_checkpointing: false # 是否使用梯度檢查點 (節省顯存但降低速度)

# 訓練相關配置 - 效能優化設置
train:
  learning_rate: 0.002            # 學習率
  weight_decay: 0.00005          # 權重衰減 (科學記數法改為小數點形式)
  epochs: 50                      # 訓練輪數
  patience: 5                     # 早停耐心值
  batch_size: 1024                # 批次大小

  # 記憶體優化相關配置
  use_dynamic_batch_size: true    # 動態調整批次大小
  memory_threshold: 0.8           # 記憶體閾值
  use_progressive_training: true  # 使用漸進式訓練
  progressive_training_initial_ratio: 0.5  # 初始比例
  progressive_training_growth_rate: 0.2    # 成長率

# 檢測相關配置
detection:
  threshold: 0.65                 # 檢測閾值
  window_size: 60                 # 窗口大小
  use_sliding_window: true        # 使用滑動窗口
  sliding_window_size: 120        # 滑動窗口大小
  sliding_window_step: 40         # 滑動窗口步長

# 輸出相關配置
output:
  model_dir: "./recode/models_fast_accurate"        # 模型儲存路徑
  result_dir: "./recode/results_fast_accurate"      # 結果儲存路徑
  visualization_dir: "./recode/vis_fast_accurate"   # 視覺化儲存路徑
  memory_report_dir: "./recode/memory_reports_fast" # 記憶體報告路徑
  checkpoint_dir: "./recode/checkpoints_fast"       # 檢查點儲存路徑

# 系統相關配置 - 效能優化設置
system:
  seed: 42                        # 隨機種子
  device: "cuda"                  # 使用設備
  gpu_id: 0                       # GPU ID
  num_workers: 8                  # 工作線程數
  pin_memory: true                # 使用固定記憶體

  # 記憶體優化相關配置
  monitor_memory: false           # 是否監控記憶體
  memory_monitor_interval: 300    # 監控間隔
  clean_memory_interval: 30       # 清理間隔
  limit_gpu_memory: 0             # 限制GPU記憶體 (0表示不限制)
